---
name: "e2e-deploy-mg"

on:
  push:
    branches:
      - main
    paths:
      - 'referenceImplementations/core/managementGroupTemplates/**'
  workflow_dispatch:

permissions:
    id-token: write
    contents: write
    pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  modulesFolder: "~/.local/share/powershell/Modules"

jobs:

  alpha:

    name: "alpha"
    runs-on: ubuntu-latest
    environment: alpha

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "azure login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'install modules'
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: get alpha-context
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
          azPSVersion: "latest"

      - name: 'get alpha Management Group'
        shell: pwsh
        run: |
          Get-AzManagementGroup

      - name: 'import deployment script'
        shell: pwsh
        run: ./deployment/Invoke-AzDeployment.ps1

      - name: 'deploy Alpha'
        shell: pwsh
        run: |
           Invoke-AzDeployment -managementGroup -enviornment alpha -path ./referenceImplementations/core/managementGroupTemplates/policyAssignments/platform/ -DeploymentName policy
 ########################################################################
 #                       G  O   L   D                                   #
 ########################################################################


  gold:
    needs: alpha

    name: "gold"
    runs-on: ubuntu-latest
    environment: gold

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "azure login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'modules'
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: 'Get Gold Management Group'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
          azPSVersion: "latest"

      - name: 'Deploy Gold'
        shell: pwsh
        run: |
          Get-AzManagementGroup