---
name: "e2e-deploy-mg"

on:
  push:
    branches:
      - main
    paths:
      - 'referenceImplementations/core/managementGroupTemplates/**'
  workflow_dispatch:

permissions:
    id-token: write
    contents: write
    pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  modulesFolder: "~/.local/share/powershell/Modules"

jobs:

  alpha:

    name: "alpha"
    runs-on: ubuntu-latest
    environment: alpha

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "azure login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'modules'
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: alpha-context
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
          azPSVersion: "latest"

      - name: 'Get Alpha Management Group'
        shell: pwsh
        run: |
          Get-AzManagementGroup

      - name: 'Deploy Alpha'
        shell: pwsh
        run: |
           $enviornment = 'alpha'
           Write-Host "Enviornment: $enviornment"
           Write-Warning "Enviornment: $enviornment"
           Get-ChildItem -Recurse -Path referenceImplementations/core/managementGroupTemplates/ -Filter *.json -Exclude *.gold.json, *.alpha.json  | % {

            Write-Host "Processing Deployment: $_"

            $rootMgmtName = Get-AzManagementGroup -GroupName $enviornment -ErrorVariable errorVariable -ErrorAction SilentlyContinue
            $managementGroupID = ($errorVariable) ? ((Get-AzContext).Tenant.Id) :($rootMgmtName).Id
            $parameterFile = (Join-Path $_.Directory.FullName -ChildPath ($_.BaseName + ".parameters." + $enviornment + $_.Extension))

            $parameters = @{
                'Name'                        = 'azops'
                'Location'                    = 'eastus'
                'ManagementGroupId'           = $managementGroupID
                'TemplateFile'                = $_.FullName
                'TemplateParameterFile'       = ((Test-Path $parameterFile) ? $parameterFile : "./emptyParameters.json")
                #'TemplateParameterObject'     = @{scope='alpha'}
                'SkipTemplateParameterPrompt' = $true
            }
            $deploymentCommand = 'New-AzManagementGroupDeployment'
            Write-Host "Starting : $deploymentCommand"
            New-AzManagementGroupDeployment @parameters
           }
 ########################################################################
 #                       G  O   L   D                                   #
 ########################################################################


  gold:
    needs: alpha

    name: "gold"
    runs-on: ubuntu-latest
    environment: gold

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "azure login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'modules'
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: 'Get Gold Management Group'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzContext
          azPSVersion: "latest"

      - name: 'Deploy Gold'
        shell: pwsh
        run: |
          Get-AzManagementGroup