---
name: "e2e-deploy"

on:

  #
  # Push
  # Automated workflow trigger when a merge
  # commit enters the main branch.
  #

  push:
    branches:
      - main
  workflow_dispatch:
      
#
# Permissions required for the pipeline to interact with repo and federated credentials
#

permissions:
    id-token: write
    contents: write
    pull-requests: write
    
env:

  #
  # Credentials
  #

  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ENVIRONMENT: ${{ secrets.ARM_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  #
  # modulesFolder
  # To enable caching of PowerShell modules between
  # runs, the modules are stored in a modules folder
  # that can be cached.
  #
  
  modulesFolder: "~/.local/share/powershell/Modules"

jobs:

  push:

    name: "alpha"
    runs-on: ubuntu-20.04
    environment: alpha

    steps:

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      – name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
     
      - name: 'Deploy'
        shell: pwsh
        run: |
          Get-AzContext | fl
        
